import React from "react";
const columns = [
  { name: "NOMBRE", uid: "name" },
  { name: "ROL", uid: "role" },
  { name: "UBICACIÓN", uid: "status" },
  { name: "EDICIÓN", uid: "actions" },
];

const users = [
  {
    id: 1,
    name: "Abraham Emmanuel González Rincón",
    role: "Alumno",
    team: "Desarrollo de Software",
    status: "dentro",
    age: "18",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "abraham.gonzalez6862@alumnos.udg.mx",
  },
  {
    id: 2,
    name: "David Sebastian Rico Vela",
    role: "Alumno",
    team: "Desarrollo de Software",
    status: "fuera",
    age: "18",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "david.rico6961@alumnos.udg.mx",
  },
  {
    id: 3,
    name: "Diego Chavez Dorado",
    role: "Alumno",
    team: "Desarrollo de Software",
    status: "dentro",
    age: "17",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "diego.chavez6884@alumnos.udg.mx",
  },
  {
    id: 4,
    name: "Arantza Ortiz Cabrera",
    role: "Alumno",
    team: "Desarrollo Industrial",
    status: "desconocido",
    age: "17",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "arantza.ortiz6954@alumnos.udg.mx",
  },
  {
    id: 5,
    name: "Israel de Jesús Beltrán Lopéz",
    role: "Alumno",
    team: "Competencias Generales",
    status: "dentro",
    age: "19",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "israel.beltran6866@alumnos.udg.mx",
  },
  {
    id: 6,
    name: "Abraham Emmanuel González Rincón",
    role: "Alumno",
    team: "Desarrollo de Software",
    status: "dentro",
    age: "18",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "abraham.gonzalez6862@alumnos.udg.mx",
  },
  {
    id: 7,
    name: "David Sebastian Rico Vela",
    role: "Alumno",
    team: "Desarrollo de Software",
    status: "fuera",
    age: "18",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "david.rico6961@alumnos.udg.mx",
  },
  {
    id: 8,
    name: "Diego Chavez Dorado",
    role: "Alumno",
    team: "Desarrollo de Software",
    status: "dentro",
    age: "17",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "diego.chavez6884@alumnos.udg.mx",
  },
  {
    id: 9,
    name: "Arantza Ortiz Cabrera",
    role: "Alumno",
    team: "Desarrollo Industrial",
    status: "desconocido",
    age: "17",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "arantza.ortiz6954@alumnos.udg.mx",
  },
  {
    id: 10,
    name: "Israel de Jesús Beltrán Lopéz",
    role: "Alumno",
    team: "Competencias Generales",
    status: "dentro",
    age: "19",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "israel.beltran6866@alumnos.udg.mx",
  },
  {
    id: 11,
    name: "Abraham Emmanuel González Rincón",
    role: "Alumno",
    team: "Desarrollo de Software",
    status: "dentro",
    age: "18",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "abraham.gonzalez6862@alumnos.udg.mx",
  },
  {
    id: 12,
    name: "David Sebastian Rico Vela",
    role: "Alumno",
    team: "Desarrollo de Software",
    status: "fuera",
    age: "18",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "david.rico6961@alumnos.udg.mx",
  },
  {
    id: 13,
    name: "Diego Chavez Dorado",
    role: "Alumno",
    team: "Desarrollo de Software",
    status: "dentro",
    age: "17",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "diego.chavez6884@alumnos.udg.mx",
  },
  {
    id: 14,
    name: "Arantza Ortiz Cabrera",
    role: "Alumno",
    team: "Desarrollo Industrial",
    status: "desconocido",
    age: "17",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "arantza.ortiz6954@alumnos.udg.mx",
  },
  {
    id: 15,
    name: "Israel de Jesús Beltrán Lopéz",
    role: "Alumno",
    team: "Competencias Generales",
    status: "dentro",
    age: "19",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "israel.beltran6866@alumnos.udg.mx",
  },
  {
    id: 16,
    name: "Abraham Emmanuel González Rincón",
    role: "Alumno",
    team: "Desarrollo de Software",
    status: "dentro",
    age: "18",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "abraham.gonzalez6862@alumnos.udg.mx",
  },
  {
    id: 17,
    name: "David Sebastian Rico Vela",
    role: "Alumno",
    team: "Desarrollo de Software",
    status: "fuera",
    age: "18",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "david.rico6961@alumnos.udg.mx",
  },
  {
    id: 18,
    name: "Diego Chavez Dorado",
    role: "Alumno",
    team: "Desarrollo de Software",
    status: "dentro",
    age: "17",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "diego.chavez6884@alumnos.udg.mx",
  },
  {
    id: 19,
    name: "Arantza Ortiz Cabrera",
    role: "Alumno",
    team: "Desarrollo Industrial",
    status: "desconocido",
    age: "17",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "arantza.ortiz6954@alumnos.udg.mx",
  },
  {
    id: 20,
    name: "Israel de Jesús Beltrán Lopéz",
    role: "Alumno",
    team: "Competencias Generales",
    status: "dentro",
    age: "19",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "israel.beltran6866@alumnos.udg.mx",
  },
];

export { columns, users };